### ISSUE TITLE
.depravity::after glue a D after the word depravity

### ISSUE THREAD

**Issue by xrogaan** [BlueWinds/Hive#1]
![2015-08-15_04-23-41](https://cloud.githubusercontent.com/assets/74860/9287091/b1b06f68-4305-11e5-9e5a-45cc214ffac4.png)
As shown on the image, the [little bit of code right there](https://github.com/BlueWinds/Hive/blob/23b32b282a96f2914c58c47289495f1029281c02/src/engine/style.css#L616) glue a D on the word Depravity. I don't know if the "D" is intentional but it's a bit weird.

I could fix that myself (by removing the piece of code), but I'm not familiar with your workflow or even if you edit the .css files directly.

Thanks for your work :heart:

**Comment by BlueWinds** [comment]
Hey. What I ended up doing here was remove the word "Depravity", rather than the .depravity class - the ::after "D" is used all over the place, so it definitely shouldn't be taken away.
