### ISSUE TITLE
Changed max attributes are not saved

### ISSUE THREAD

**Issue by plkmjn** [BlueWinds/Hive#15]
Hi blue,

I'm playing the web version (http://hive.winds.blue/) with bugfix 16/9/3: Load the attached save (github doesn't like .yaml) -> next day -> the max attributes of people in the spawning pit changed properly. Now I save and load immediately, the changes to max attributes are lost, and if I export the save and read it in a text editor there is no trace of changed max attributes.

Also a GUI bug: The milking barn should say already full instead of need female.

[Day161-NorthEnd-45D.txt](https://github.com/BlueWinds/Hive/files/454061/Day161-NorthEnd-45D.txt)

**Comment by BlueWinds** [comment]
Fixed in 0.9.0, though it that was annoyingly hard to track down. Thanks for the report. :)

I did forget to change the milking barn. I'll include that fix in the next release.
