### ISSUE TITLE
In the gym +#{effect} shows the function instead of the result if the dark lady go to train.

### ISSUE THREAD

**Issue by xrogaan** [BlueWinds/Hive#3]
![2015-08-15_05-33-06](https://cloud.githubusercontent.com/assets/74860/9287324/25986c4c-430f-11e5-8d03-9f6599e26892.png)

https://github.com/BlueWinds/Hive/blob/23b32b282a96f2914c58c47289495f1029281c02/src/content/rooms/gym.coffee#L45

**Comment by BlueWinds** [comment]
In general, I prefer bug reports on the blog. I know it's annoying not to be able to upload images there, but darned wordpress won't make that easy. :)

Fixed in a commit coming in shortly.
